# Generated by Django 5.0 on 2024-01-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=150)),
                ('comments', models.CharField(max_length=150)),
            ],
        ),
    ]
