# Generated by Django 5.0 on 2024-01-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_Name', models.CharField(max_length=200)),
                ('Comments', models.TextField()),
            ],
        ),
    ]
